#!/usr/bin/env python3
"""Regenerates mobile number lengths from Google's libphonenumber metadata.

Writes the same data to two places, which must agree:

- `Mobile_Number_Lengths` on each entry of `assets/resources/countries.json`,
  keyed by ISO 3166-1 alpha-2 code, read into `Country.mobileNumberLengths`;
- `lib/data/constants/phone_lengths.dart`, keyed by ITU calling code, which
  the phone canonicaliser and validator read synchronously.

Only the metadata file is used; libphonenumber itself is not a dependency.

Usage, from the package root:

    python3 tool/generate_phone_lengths.py [libphonenumber-ref]
"""

import collections
import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

REF = sys.argv[1] if len(sys.argv) > 1 else "0ae309f1940227efe688f5eb1815ef45a6fbee8d"
URL = (
    "https://raw.githubusercontent.com/google/libphonenumber/"
    f"{REF}/resources/PhoneNumberMetadata.xml"
)
COUNTRIES = "assets/resources/countries.json"
DART = "lib/data/constants/phone_lengths.dart"

# Territories that are not countries, such as satellite and toll-free
# services, share this id and are left out.
NON_GEOGRAPHIC = "001"


def parse_lengths(spec):
    """`[8-10],12` becomes `[8, 9, 10, 12]`; `-1` means none."""
    lengths = set()
    for part in (spec or "").split(","):
        part = part.strip()
        if not part or part == "-1":
            continue
        span = re.fullmatch(r"\[(\d+)-(\d+)\]", part)
        if span:
            lengths.update(range(int(span[1]), int(span[2]) + 1))
            continue
        lengths.add(int(part))
    return sorted(lengths)


def mobile_lengths(territory):
    mobile = territory.find("mobile")
    if mobile is None:
        return None
    possible = mobile.find("possibleLengths")
    if possible is None:
        return None
    return parse_lengths(possible.get("national")) or None


def load_metadata():
    # curl rather than urllib, which fails on Python builds without the
    # system certificates, such as python.org's on macOS.
    download = subprocess.run(["curl", "-sSfL", URL], capture_output=True, check=True)
    root = ET.fromstring(download.stdout)

    by_iso = {}
    by_code = collections.defaultdict(set)
    for territory in root.iter("territory"):
        iso = territory.get("id")
        lengths = mobile_lengths(territory)
        if iso == NON_GEOGRAPHIC or not lengths:
            continue
        by_iso[iso] = lengths
        by_code[territory.get("countryCode")].update(lengths)
    return by_iso, {code: sorted(lengths) for code, lengths in by_code.items()}


def write_countries(by_iso):
    with open(COUNTRIES, encoding="utf-8") as file:
        countries = json.load(file)

    updated = []
    for country in countries:
        entry = {k: v for k, v in country.items() if k != "Mobile_Number_Lengths"}
        ordered = {}
        for key, value in entry.items():
            ordered[key] = value
            if key == "MARC":
                ordered["Mobile_Number_Lengths"] = by_iso.get(
                    country["ISO3166_1_Alpha_2"]
                )
        updated.append(ordered)

    with open(COUNTRIES, "w", encoding="utf-8") as file:
        file.write(json.dumps(updated, separators=(",", ":"), ensure_ascii=False))


def write_dart(by_code):
    entries = "\n".join(
        f"    '{code}': {lengths},"
        for code, lengths in sorted(by_code.items(), key=lambda it: int(it[0]))
    )
    source = f"""/// {{@category Data}}
/// The lengths a mobile number can have after its ITU calling code, with no
/// trunk `0`, keyed by that calling code: `'234': [10]` for Nigeria.
///
/// Where territories share a calling code, their lengths are merged.
///
/// Generated by `tool/generate_phone_lengths.py` from libphonenumber's
/// `PhoneNumberMetadata.xml` (Apache-2.0) at commit
/// `{REF}`.
///
/// Do not edit by hand; the same data is in `assets/resources/countries.json`.
class AppPhoneLengths {{
  static const Map<String, List<int>> mobileByCallingCode = {{
{entries}
  }};
}}
"""
    with open(DART, "w", encoding="utf-8") as file:
        file.write(source)
    subprocess.run(["dart", "format", DART], check=True)


def main():
    by_iso, by_code = load_metadata()
    write_countries(by_iso)
    write_dart(by_code)


if __name__ == "__main__":
    main()
