name: Deploy Widgetbook to GitHub Pages

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.state == 'closed' &&
        github.event.pull_request.merged == true
      ) || (github.event_name == 'push' && github.ref_type == 'tag')
    permissions:
      contents: write # Required for publishing to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Docs
        run: dart doc --output=docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder where flutter builds the web files
          branch: gh-pages # The branch the action should deploy to
          clean: true
